# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc “Push a new beta build to TestFlight”
  lane :beta do
  increment_build_number(xcodeproj: "CICDDemo.xcodeproj")
  build_app(scheme: "CICDDemo")
  upload_to_testflight
  end

  lane :tests do
  run_tests(workspace: “CICDDemo.xcworkspace”,
  devices: ["iPhone 8"],
  scheme: "CICDDemo",
  skip_build: true)
  end

  lane :testsWithoutBuild do
  run_tests(
  run_tests(workspace: “CICDDemo.xcworkspace”,
  devices: [“iPhone 8”],
  scheme: “CICDDemo — Prod”),
  test_without_building: true)
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
